// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Execution.proto

package com.css.proto;

public final class ExecProtos {
  private ExecProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ExecMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.css.proto.ExecMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 exec_order_id = 1;</code>
     */
    int getExecOrderId();

    /**
     * <code>int32 exec_id = 2;</code>
     */
    int getExecId();

    /**
     * <code>int32 quantity = 3;</code>
     */
    int getQuantity();

    /**
     * <code>float price = 4;</code>
     */
    float getPrice();

    /**
     * <code>int32 trade_date = 5;</code>
     */
    int getTradeDate();

    /**
     * <code>int32 settle_date = 6;</code>
     */
    int getSettleDate();

    /**
     * <code>string exec_status = 7;</code>
     */
    java.lang.String getExecStatus();
    /**
     * <code>string exec_status = 7;</code>
     */
    com.google.protobuf.ByteString
        getExecStatusBytes();

    /**
     * <code>string exec_comment = 8;</code>
     */
    java.lang.String getExecComment();
    /**
     * <code>string exec_comment = 8;</code>
     */
    com.google.protobuf.ByteString
        getExecCommentBytes();

    /**
     * <code>int64 exec_time = 9;</code>
     */
    long getExecTime();

    /**
     * <code>int64 audit_time = 10;</code>
     */
    long getAuditTime();

    /**
     * <code>string audit_user = 11;</code>
     */
    java.lang.String getAuditUser();
    /**
     * <code>string audit_user = 11;</code>
     */
    com.google.protobuf.ByteString
        getAuditUserBytes();
  }
  /**
   * Protobuf type {@code com.css.proto.ExecMessage}
   */
  public  static final class ExecMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.css.proto.ExecMessage)
      ExecMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ExecMessage.newBuilder() to construct.
    private ExecMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ExecMessage() {
      execStatus_ = "";
      execComment_ = "";
      auditUser_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ExecMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              execOrderId_ = input.readInt32();
              break;
            }
            case 16: {

              execId_ = input.readInt32();
              break;
            }
            case 24: {

              quantity_ = input.readInt32();
              break;
            }
            case 37: {

              price_ = input.readFloat();
              break;
            }
            case 40: {

              tradeDate_ = input.readInt32();
              break;
            }
            case 48: {

              settleDate_ = input.readInt32();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              execStatus_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              execComment_ = s;
              break;
            }
            case 72: {

              execTime_ = input.readInt64();
              break;
            }
            case 80: {

              auditTime_ = input.readInt64();
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              auditUser_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.css.proto.ExecProtos.internal_static_com_css_proto_ExecMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.css.proto.ExecProtos.internal_static_com_css_proto_ExecMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.css.proto.ExecProtos.ExecMessage.class, com.css.proto.ExecProtos.ExecMessage.Builder.class);
    }

    public static final int EXEC_ORDER_ID_FIELD_NUMBER = 1;
    private int execOrderId_;
    /**
     * <code>int32 exec_order_id = 1;</code>
     */
    public int getExecOrderId() {
      return execOrderId_;
    }

    public static final int EXEC_ID_FIELD_NUMBER = 2;
    private int execId_;
    /**
     * <code>int32 exec_id = 2;</code>
     */
    public int getExecId() {
      return execId_;
    }

    public static final int QUANTITY_FIELD_NUMBER = 3;
    private int quantity_;
    /**
     * <code>int32 quantity = 3;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    public static final int PRICE_FIELD_NUMBER = 4;
    private float price_;
    /**
     * <code>float price = 4;</code>
     */
    public float getPrice() {
      return price_;
    }

    public static final int TRADE_DATE_FIELD_NUMBER = 5;
    private int tradeDate_;
    /**
     * <code>int32 trade_date = 5;</code>
     */
    public int getTradeDate() {
      return tradeDate_;
    }

    public static final int SETTLE_DATE_FIELD_NUMBER = 6;
    private int settleDate_;
    /**
     * <code>int32 settle_date = 6;</code>
     */
    public int getSettleDate() {
      return settleDate_;
    }

    public static final int EXEC_STATUS_FIELD_NUMBER = 7;
    private volatile java.lang.Object execStatus_;
    /**
     * <code>string exec_status = 7;</code>
     */
    public java.lang.String getExecStatus() {
      java.lang.Object ref = execStatus_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        execStatus_ = s;
        return s;
      }
    }
    /**
     * <code>string exec_status = 7;</code>
     */
    public com.google.protobuf.ByteString
        getExecStatusBytes() {
      java.lang.Object ref = execStatus_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        execStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXEC_COMMENT_FIELD_NUMBER = 8;
    private volatile java.lang.Object execComment_;
    /**
     * <code>string exec_comment = 8;</code>
     */
    public java.lang.String getExecComment() {
      java.lang.Object ref = execComment_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        execComment_ = s;
        return s;
      }
    }
    /**
     * <code>string exec_comment = 8;</code>
     */
    public com.google.protobuf.ByteString
        getExecCommentBytes() {
      java.lang.Object ref = execComment_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        execComment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXEC_TIME_FIELD_NUMBER = 9;
    private long execTime_;
    /**
     * <code>int64 exec_time = 9;</code>
     */
    public long getExecTime() {
      return execTime_;
    }

    public static final int AUDIT_TIME_FIELD_NUMBER = 10;
    private long auditTime_;
    /**
     * <code>int64 audit_time = 10;</code>
     */
    public long getAuditTime() {
      return auditTime_;
    }

    public static final int AUDIT_USER_FIELD_NUMBER = 11;
    private volatile java.lang.Object auditUser_;
    /**
     * <code>string audit_user = 11;</code>
     */
    public java.lang.String getAuditUser() {
      java.lang.Object ref = auditUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        auditUser_ = s;
        return s;
      }
    }
    /**
     * <code>string audit_user = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAuditUserBytes() {
      java.lang.Object ref = auditUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        auditUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (execOrderId_ != 0) {
        output.writeInt32(1, execOrderId_);
      }
      if (execId_ != 0) {
        output.writeInt32(2, execId_);
      }
      if (quantity_ != 0) {
        output.writeInt32(3, quantity_);
      }
      if (price_ != 0F) {
        output.writeFloat(4, price_);
      }
      if (tradeDate_ != 0) {
        output.writeInt32(5, tradeDate_);
      }
      if (settleDate_ != 0) {
        output.writeInt32(6, settleDate_);
      }
      if (!getExecStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, execStatus_);
      }
      if (!getExecCommentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, execComment_);
      }
      if (execTime_ != 0L) {
        output.writeInt64(9, execTime_);
      }
      if (auditTime_ != 0L) {
        output.writeInt64(10, auditTime_);
      }
      if (!getAuditUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, auditUser_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (execOrderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, execOrderId_);
      }
      if (execId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, execId_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quantity_);
      }
      if (price_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, price_);
      }
      if (tradeDate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, tradeDate_);
      }
      if (settleDate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, settleDate_);
      }
      if (!getExecStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, execStatus_);
      }
      if (!getExecCommentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, execComment_);
      }
      if (execTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, execTime_);
      }
      if (auditTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, auditTime_);
      }
      if (!getAuditUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, auditUser_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.css.proto.ExecProtos.ExecMessage)) {
        return super.equals(obj);
      }
      com.css.proto.ExecProtos.ExecMessage other = (com.css.proto.ExecProtos.ExecMessage) obj;

      if (getExecOrderId()
          != other.getExecOrderId()) return false;
      if (getExecId()
          != other.getExecId()) return false;
      if (getQuantity()
          != other.getQuantity()) return false;
      if (java.lang.Float.floatToIntBits(getPrice())
          != java.lang.Float.floatToIntBits(
              other.getPrice())) return false;
      if (getTradeDate()
          != other.getTradeDate()) return false;
      if (getSettleDate()
          != other.getSettleDate()) return false;
      if (!getExecStatus()
          .equals(other.getExecStatus())) return false;
      if (!getExecComment()
          .equals(other.getExecComment())) return false;
      if (getExecTime()
          != other.getExecTime()) return false;
      if (getAuditTime()
          != other.getAuditTime()) return false;
      if (!getAuditUser()
          .equals(other.getAuditUser())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXEC_ORDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getExecOrderId();
      hash = (37 * hash) + EXEC_ID_FIELD_NUMBER;
      hash = (53 * hash) + getExecId();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPrice());
      hash = (37 * hash) + TRADE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getTradeDate();
      hash = (37 * hash) + SETTLE_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getSettleDate();
      hash = (37 * hash) + EXEC_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getExecStatus().hashCode();
      hash = (37 * hash) + EXEC_COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getExecComment().hashCode();
      hash = (37 * hash) + EXEC_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecTime());
      hash = (37 * hash) + AUDIT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAuditTime());
      hash = (37 * hash) + AUDIT_USER_FIELD_NUMBER;
      hash = (53 * hash) + getAuditUser().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.css.proto.ExecProtos.ExecMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.css.proto.ExecProtos.ExecMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.css.proto.ExecProtos.ExecMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.css.proto.ExecMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.css.proto.ExecMessage)
        com.css.proto.ExecProtos.ExecMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.css.proto.ExecProtos.internal_static_com_css_proto_ExecMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.css.proto.ExecProtos.internal_static_com_css_proto_ExecMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.css.proto.ExecProtos.ExecMessage.class, com.css.proto.ExecProtos.ExecMessage.Builder.class);
      }

      // Construct using com.css.proto.ExecProtos.ExecMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        execOrderId_ = 0;

        execId_ = 0;

        quantity_ = 0;

        price_ = 0F;

        tradeDate_ = 0;

        settleDate_ = 0;

        execStatus_ = "";

        execComment_ = "";

        execTime_ = 0L;

        auditTime_ = 0L;

        auditUser_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.css.proto.ExecProtos.internal_static_com_css_proto_ExecMessage_descriptor;
      }

      @java.lang.Override
      public com.css.proto.ExecProtos.ExecMessage getDefaultInstanceForType() {
        return com.css.proto.ExecProtos.ExecMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.css.proto.ExecProtos.ExecMessage build() {
        com.css.proto.ExecProtos.ExecMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.css.proto.ExecProtos.ExecMessage buildPartial() {
        com.css.proto.ExecProtos.ExecMessage result = new com.css.proto.ExecProtos.ExecMessage(this);
        result.execOrderId_ = execOrderId_;
        result.execId_ = execId_;
        result.quantity_ = quantity_;
        result.price_ = price_;
        result.tradeDate_ = tradeDate_;
        result.settleDate_ = settleDate_;
        result.execStatus_ = execStatus_;
        result.execComment_ = execComment_;
        result.execTime_ = execTime_;
        result.auditTime_ = auditTime_;
        result.auditUser_ = auditUser_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.css.proto.ExecProtos.ExecMessage) {
          return mergeFrom((com.css.proto.ExecProtos.ExecMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.css.proto.ExecProtos.ExecMessage other) {
        if (other == com.css.proto.ExecProtos.ExecMessage.getDefaultInstance()) return this;
        if (other.getExecOrderId() != 0) {
          setExecOrderId(other.getExecOrderId());
        }
        if (other.getExecId() != 0) {
          setExecId(other.getExecId());
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        if (other.getTradeDate() != 0) {
          setTradeDate(other.getTradeDate());
        }
        if (other.getSettleDate() != 0) {
          setSettleDate(other.getSettleDate());
        }
        if (!other.getExecStatus().isEmpty()) {
          execStatus_ = other.execStatus_;
          onChanged();
        }
        if (!other.getExecComment().isEmpty()) {
          execComment_ = other.execComment_;
          onChanged();
        }
        if (other.getExecTime() != 0L) {
          setExecTime(other.getExecTime());
        }
        if (other.getAuditTime() != 0L) {
          setAuditTime(other.getAuditTime());
        }
        if (!other.getAuditUser().isEmpty()) {
          auditUser_ = other.auditUser_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.css.proto.ExecProtos.ExecMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.css.proto.ExecProtos.ExecMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int execOrderId_ ;
      /**
       * <code>int32 exec_order_id = 1;</code>
       */
      public int getExecOrderId() {
        return execOrderId_;
      }
      /**
       * <code>int32 exec_order_id = 1;</code>
       */
      public Builder setExecOrderId(int value) {
        
        execOrderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 exec_order_id = 1;</code>
       */
      public Builder clearExecOrderId() {
        
        execOrderId_ = 0;
        onChanged();
        return this;
      }

      private int execId_ ;
      /**
       * <code>int32 exec_id = 2;</code>
       */
      public int getExecId() {
        return execId_;
      }
      /**
       * <code>int32 exec_id = 2;</code>
       */
      public Builder setExecId(int value) {
        
        execId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 exec_id = 2;</code>
       */
      public Builder clearExecId() {
        
        execId_ = 0;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 3;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 3;</code>
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 3;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 4;</code>
       */
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 4;</code>
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 4;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0F;
        onChanged();
        return this;
      }

      private int tradeDate_ ;
      /**
       * <code>int32 trade_date = 5;</code>
       */
      public int getTradeDate() {
        return tradeDate_;
      }
      /**
       * <code>int32 trade_date = 5;</code>
       */
      public Builder setTradeDate(int value) {
        
        tradeDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 trade_date = 5;</code>
       */
      public Builder clearTradeDate() {
        
        tradeDate_ = 0;
        onChanged();
        return this;
      }

      private int settleDate_ ;
      /**
       * <code>int32 settle_date = 6;</code>
       */
      public int getSettleDate() {
        return settleDate_;
      }
      /**
       * <code>int32 settle_date = 6;</code>
       */
      public Builder setSettleDate(int value) {
        
        settleDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 settle_date = 6;</code>
       */
      public Builder clearSettleDate() {
        
        settleDate_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object execStatus_ = "";
      /**
       * <code>string exec_status = 7;</code>
       */
      public java.lang.String getExecStatus() {
        java.lang.Object ref = execStatus_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          execStatus_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exec_status = 7;</code>
       */
      public com.google.protobuf.ByteString
          getExecStatusBytes() {
        java.lang.Object ref = execStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          execStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exec_status = 7;</code>
       */
      public Builder setExecStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        execStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exec_status = 7;</code>
       */
      public Builder clearExecStatus() {
        
        execStatus_ = getDefaultInstance().getExecStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string exec_status = 7;</code>
       */
      public Builder setExecStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        execStatus_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object execComment_ = "";
      /**
       * <code>string exec_comment = 8;</code>
       */
      public java.lang.String getExecComment() {
        java.lang.Object ref = execComment_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          execComment_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exec_comment = 8;</code>
       */
      public com.google.protobuf.ByteString
          getExecCommentBytes() {
        java.lang.Object ref = execComment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          execComment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exec_comment = 8;</code>
       */
      public Builder setExecComment(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        execComment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string exec_comment = 8;</code>
       */
      public Builder clearExecComment() {
        
        execComment_ = getDefaultInstance().getExecComment();
        onChanged();
        return this;
      }
      /**
       * <code>string exec_comment = 8;</code>
       */
      public Builder setExecCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        execComment_ = value;
        onChanged();
        return this;
      }

      private long execTime_ ;
      /**
       * <code>int64 exec_time = 9;</code>
       */
      public long getExecTime() {
        return execTime_;
      }
      /**
       * <code>int64 exec_time = 9;</code>
       */
      public Builder setExecTime(long value) {
        
        execTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 exec_time = 9;</code>
       */
      public Builder clearExecTime() {
        
        execTime_ = 0L;
        onChanged();
        return this;
      }

      private long auditTime_ ;
      /**
       * <code>int64 audit_time = 10;</code>
       */
      public long getAuditTime() {
        return auditTime_;
      }
      /**
       * <code>int64 audit_time = 10;</code>
       */
      public Builder setAuditTime(long value) {
        
        auditTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 audit_time = 10;</code>
       */
      public Builder clearAuditTime() {
        
        auditTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object auditUser_ = "";
      /**
       * <code>string audit_user = 11;</code>
       */
      public java.lang.String getAuditUser() {
        java.lang.Object ref = auditUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          auditUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string audit_user = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAuditUserBytes() {
        java.lang.Object ref = auditUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          auditUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string audit_user = 11;</code>
       */
      public Builder setAuditUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        auditUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string audit_user = 11;</code>
       */
      public Builder clearAuditUser() {
        
        auditUser_ = getDefaultInstance().getAuditUser();
        onChanged();
        return this;
      }
      /**
       * <code>string audit_user = 11;</code>
       */
      public Builder setAuditUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        auditUser_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.css.proto.ExecMessage)
    }

    // @@protoc_insertion_point(class_scope:com.css.proto.ExecMessage)
    private static final com.css.proto.ExecProtos.ExecMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.css.proto.ExecProtos.ExecMessage();
    }

    public static com.css.proto.ExecProtos.ExecMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExecMessage>
        PARSER = new com.google.protobuf.AbstractParser<ExecMessage>() {
      @java.lang.Override
      public ExecMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExecMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ExecMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExecMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.css.proto.ExecProtos.ExecMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_css_proto_ExecMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_css_proto_ExecMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Execution.proto\022\rcom.css.proto\"\345\001\n\013Exe" +
      "cMessage\022\025\n\rexec_order_id\030\001 \001(\005\022\017\n\007exec_" +
      "id\030\002 \001(\005\022\020\n\010quantity\030\003 \001(\005\022\r\n\005price\030\004 \001(" +
      "\002\022\022\n\ntrade_date\030\005 \001(\005\022\023\n\013settle_date\030\006 \001" +
      "(\005\022\023\n\013exec_status\030\007 \001(\t\022\024\n\014exec_comment\030" +
      "\010 \001(\t\022\021\n\texec_time\030\t \001(\003\022\022\n\naudit_time\030\n" +
      " \001(\003\022\022\n\naudit_user\030\013 \001(\tB\033\n\rcom.css.prot" +
      "oB\nExecProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_css_proto_ExecMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_css_proto_ExecMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_css_proto_ExecMessage_descriptor,
        new java.lang.String[] { "ExecOrderId", "ExecId", "Quantity", "Price", "TradeDate", "SettleDate", "ExecStatus", "ExecComment", "ExecTime", "AuditTime", "AuditUser", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
